# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false   
# disable in dev mode (so changes reflect without restart)

# ===============================
# Static Resources
# ===============================
spring.web.resources.static-locations=classpath:/static/

# ===============================
# Server Port
# ===============================
server.port=8080   
# Port value

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=DEBUG
logging.level.enrollment.courseenrollment=DEBUG

# ===============================
# 404 Exception handler
# ===============================
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

